server:
  port: 8080

spring:
  profiles:
    active: dev,dummy-data
  config:
    import:
      - optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

security:
  public-urls:
    # 클라이언트 기반 소셜 로그인
    - "/api/auth/social/login"
    # JWT 토큰 관리
    - "/api/auth/token/refresh"
    - "/api/auth/token/refresh/full"
    - "/api/auth/logout"
    # 개발용 API (dev 프로파일에서만)
    - "/api/dev/**"
    # API 문서
    - "/api-docs"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    # 헬스체크 (Actuator)
    - "/health"
    - "/actuator/health"
    # 일반 회원가입 제거: "/api/join", "/api/join/email-check", "/api/auth/login"
  cors-max-age: 3600

# ?? Swagger ??
springdoc:
  swagger-ui:
    path: /api-docs

logging:
  file:
    name: app.log
  level:
    root: warn
    org.springframework: warn
    com.groomthon.habiglow.domain.routine: info


# ===== Actuator 설정 (헬스체크) =====
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# ===== 대시보드/프롬프트 설정 (추가) =====
dashboard:
  weekly:
    lookback-weeks: 12
    include-dummy-last-week: true   # 시연/검증 편의상 기본 true
  ai:
    prompt:
      system-prompt: >
        You are HabiGlow Weekly Analyst.
        Purpose
        - Summarize Mon–Sun habit successes/failures and mood changes.
        - Provide exactly ONE empathy sentence and ONE encouragement sentence.
        - No blame; describe failures as patterns.
        Style (Korean, 존댓말)
        - Always write in Korean (formal, 존댓말).
        - Be concise and concrete (numbers, counts).
        - Emojis only in mood fields; others: 0–1 emoji at most.
        Output rules
        - Must follow the provided JSON schema exactly (no extra fields).
        - Length guide: weekly_summary ≤ 80 chars, empathy ≤ 80 chars, encouragement ≤ 80 chars.
      user-template: |
        아래는 사용자의 주간 스냅샷(JSON)입니다.
        반드시 스키마에 맞춘 JSON만 출력하세요.

        {snapshot}
