# 개발 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://db:5432/HabiDB
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# OpenAI 설정
openai:
  api:
    key: ${OPENAI_API_KEY:your-dev-api-key-here}
    base-url: https://api.openai.com/v1
    model: gpt-4o-mini
    timeout: 30s
    max-retries: 3

# 개발환경 쿠키 설정
cookie:
  secure: false

# 개발환경 Swagger 설정
swagger:
  server:
    url: http://localhost:8080
    description: 개발 서버

# 개발환경 로깅
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.groomthon.habiglow: debug
    # OpenAI API 호출 로깅용
    org.springframework.web.reactive.function.client: debug