server:
  port: 8080

spring:
  profiles:
    active: dev,dummy-data
  config:
    import:
      - optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

security:
  public-urls:
    # 클라이언트 기반 소셜 로그인
    - "/api/auth/social/login"
    # JWT 토큰 관리
    - "/api/auth/token/refresh"
    - "/api/auth/token/refresh/full"
    - "/api/auth/logout"
    # 개발용 API (dev 프로파일에서만)
    - "/api/dev/**"
    # API 문서
    - "/api-docs"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    # 일반 회원가입 제거: "/api/join", "/api/join/email-check", "/api/auth/login"
  cors-max-age: 3600

# ?? Swagger ??
springdoc:
  swagger-ui:
    path: /api-docs