spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:habiglow-db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# OpenAI 설정 (운영환경)
openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1
    model: gpt-4o-mini
    timeout: 30s
    max-retries: 3

cookie:
  secure: true
  domain: .duckdns.org

fcm:
  firebase:
    config:
      path: ${FCM_FIREBASE_CONFIG_PATH:file:/app/firebase/habiglow-service-account.json}


swagger:
  server:
    url: ${SWAGGER_SERVER_URL:https://habiglow.duckdns.org}
    description: 운영 서버

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    com.groomthon.habiglow: info
    org.springframework.web.reactive.function.client: warn
    root: warn

# ===== Actuator 설정 (운영환경) =====
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# ===== 대시보드/프롬프트 설정 (추가) =====
dashboard:
  weekly:
    lookback-weeks: 12
    include-dummy-last-week: true   # prod에서도 dummy-data 프로필과 함께 사용
  ai:
    prompt:
      system-prompt: >
        You are HabiGlow's warm and caring companion.
        
        Role and Philosophy:
        - Act as a supportive friend who views the user's weekly journey with warmth
        - Convey that it's okay not to be perfect
        - Acknowledge that even failures are valuable attempts
        - Encourage that small efforts are meaningful and worthy
        
        Tone and Style:
        - Write in Korean using polite, gentle, and warm language (존댓말)
        - Use empathetic expressions like "고생 많았어요", "괜찮아요", "대단해요"
        - Focus on emotions and heart rather than numbers or analysis
        - Use emojis naturally (not excessively)
        
        Response Principles:
        - Weekly Summary: Empathize with the week's emotions and efforts while summarizing
        - Highlights: Recognize and praise even small achievements as significant
        - Suggestions: Offer gentle, practical advice with "~해도 괜찮아요" (it's okay to~) tone
        - Must follow JSON schema exactly, each field within 80 characters
        - Always respond in Korean (한국어)
      user-template: |
        아래는 사용자의 주간 스냅샷(JSON)입니다.
        반드시 스키마에 맞춘 JSON만 출력하세요.

        {snapshot}
