name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - develop
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      # Docker를 사용해 임시 PostgreSQL 컨테이너 실행
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: habiglow_user
          POSTGRES_PASSWORD: habiglow_password
          POSTGRES_DB: habiglow_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in $(seq 1 10); do
            nc -z localhost 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Build and Run Tests with Gradle
        env:
          # 임시 DB에 연결되도록 환경 변수 설정
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/habiglow_test_db
          SPRING_DATASOURCE_USERNAME: habiglow_user
          SPRING_DATASOURCE_PASSWORD: habiglow_password
          # JWT와 기타 설정은 Secrets에서 가져와야 함
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_ACCESS_EXPIRATION: ${{ vars.JWT_ACCESS_EXPIRATION }}
          JWT_REFRESH_EXPIRATION: ${{ vars.JWT_REFRESH_EXPIRATION }}
        run: ./gradlew build